name       : kaffeine
version    : 2.0.9
release    : 1
source     :
    - https://github.com/KDE/kaffeine/archive/2.0.9.tar.gz : 36de0972e737a55be03246faf806fbbc0c3481943f8a7873feaa2a04f21094f1
license    : GPL-2.0
component  : desktop.multimedia
summary    : Kaffeine Media Player
description: |
    Kaffeine is a media player. What makes it different from the others is its excellent support of digital TV (DVB). Kaffeine has user-friendly interface, so that even first time users can start immediately playing their movies: from DVD (including DVD menus, titles, chapters, etc.), VCD, or a file.
builddeps  :
    - extra-cmake-modules
    - kdbusaddons-devel
    - kdoctools-devel
    - ki18n-devel
    - kio-devel
    - pkgconfig(gl)
    - pkgconfig(libdvbpsi)
    - pkgconfig(libvlc)
    - pkgconfig(Qt5Gui)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xscrnsaver)
rundeps    : 
    - kinit
setup      : |
    %cmake . -DCMAKE_BUILD_TYPE=Release \
             -DCMAKE_INSTALL_PREFIX=/usr
build      : |
    %make
install    : |
    %make_install
