name       : kaffeine
version    : 2.0.16
release    : 9
source     :
    - https://cdn.download.kde.org/stable/kaffeine/kaffeine-2.0.16-2.tar.xz : 8659189d907c2512321dd2c0d0c47176229c344970d633e33f29ce82432deee5
license    : GPL-2.0-or-later
component  : desktop.multimedia
summary    : Kaffeine Media Player
description: |
    Kaffeine is a media player. What makes it different from the others is its excellent support of digital TV (DVB). Kaffeine has user-friendly interface, so that even first time users can start immediately playing their movies: from DVD (including DVD menus, titles, chapters, etc.), VCD, or a file.
builddeps  :
    - pkgconfig(libdvbv5)
    - pkgconfig(libvlc)
    - pkgconfig(Qt5Gui)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xscrnsaver)
    - extra-cmake-modules
    - kdbusaddons-devel
    # - kdoctools-devel
    - ki18n-devel
    - kio-devel
    - kwindowsystem-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
