name       : kaffeine
version    : 2.0.15
release    : 8
source     :
    - https://cdn.download.kde.org/stable/kaffeine/kaffeine-2.0.15.tar.xz : e61573199fe4e04377679a5cf8b32b3aa0bb4201c56371e11820d3a3ae41904d
license    : GPL-2.0
component  : desktop.multimedia
summary    : Kaffeine Media Player
description: |
    Kaffeine is a media player. What makes it different from the others is its excellent support of digital TV (DVB). Kaffeine has user-friendly interface, so that even first time users can start immediately playing their movies: from DVD (including DVD menus, titles, chapters, etc.), VCD, or a file.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libdvbv5)
    - pkgconfig(libvlc)
    - pkgconfig(Qt5Gui)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xscrnsaver)
    - extra-cmake-modules
    - kdbusaddons-devel
    # - kdoctools-devel
    - ki18n-devel
    - kio-devel
    - kwindowsystem-devel
setup      : |
    %cmake . -DCMAKE_BUILD_TYPE=Release \
             -DCMAKE_INSTALL_PREFIX=/usr
build      : |
    %make
install    : |
    %make_install
